version: '3.3'
name: 'mongo'

services:
  mongo:
    image: mongo:5
    volumes: 
      - type: bind
        source: "./workspace"
        target:  "/workspace"
    container_name: 'mongo-db'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test123*